apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-order-api
spec:
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: dev-order-api
      labels:
        service: dev-order-api
    spec:
      imagePullSecrets:
        - name: dblys152-docker-secret
      terminationGracePeriodSeconds: 70
      containers:
        - name: order-api
          image: dblys152/order-api
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "test"
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent

      restartPolicy: Always
  selector:
    matchLabels:
      service: dev-order-api

---
apiVersion: v1
kind: Service
metadata:
  name: dev-order-api
spec:
  selector:
    service: dev-order-api
  ports:
    - port: 5000